[package]
name = "class-transcriber"
version = "0.1.0"
description = "A lightweight local audio and video transcription app powered by whisper.cpp."
authors = ["fivur-cs"]
edition = "2021"

[lib]
name = "class_transcriber_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tempfile = "3"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
